### ISSUE TITLE
Method get_InstalledPath doesn't exist

### ISSUE THREAD

**Issue by AndASM** [AndASM/ANMSMEMSPC#1]
Nexus Mods Report: https://www.nexusmods.com/nomanssky/mods/1751?tab=bugs&issue_id=484705
Error Text:
```
Finding No Man's Sky Installation...
Unhandled exception. System.MissingMethodException: Method not found: 'System.String Windows.ApplicationModel.Package.get_InstalledPath()',
    at AndysNMSWinStoreModFix.NmsPackage..ctor()
    at AndysNMSWinStoreModFix.Program.Main(String[] args)
```

**Comment by AndASM** [comment]
The (Microsoft Documentation)[https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.installedpath] indicates this property was added for WinRT Build 19041. That means Windows version 2004, the update for spring of 2020.

Whatever Microsoft's internal issues are, they've had trouble rolling out updates in a timely fashion, what with all the terrible bugs. Using features released within the last 2 years is probably unsafe.

InstalledLocation should probably be safe in place of InstalledPath.
